language: python

sudo: no

python:
  - 2.7
  - 3.5

env:
  global:
    - PEP=false
  matrix:
    - PANDOC=1.17

matrix:
  include:
    - python: 2.7
      env: PEP=true

before_install:
  - if ! $PEP; then source .travis.install_pandoc.sh; fi

install:
  - pip install pep8
  - pip install .

script:
  - if $PEP; then pep8 internalreferences.py; fi
  - if ! $PEP; then nosetests; fi
